### ISSUE TITLE
Some problems about using glad-fortran

### ISSUE THREAD

**Issue by lj-cug** [gadjalin/glad-fortran#1]
glad-fortran is a good tool to generate Fortran glad code integrated with glf90w. I find some problems using glda-fortran as:
(1) Python 3.9 cannot be used. I succeed to generate Fortran code gl.F90 using Python 3.13. What is the minimal  Python version?
(2) I compile gl.F90 using Intel OneAPI Fortran compiler ifx, compilation errors happened as:
gl.F90(58742): error #8284: If the actual argument is scalar, the dummy argument shall be scalar unless the actual argument is of type character or is an element of an array that is not assumed shape, pointer, or polymorphic.   [NAME]
.... many alike errors ...

The code in gl.F90 is 
`
            call glad_glGetActiveAttrib( &
                program, &
                index, &
                bufSize, &
                opt_length, &
                opt_size, &
                opt_type, &
                c_loc(name) &
            )
`
the declaration of name is
character(len=*,kind=GLchar), target :: name

What's the problem?

**Comment by gadjalin** [comment]
Thank you!
Handling the different `char const*`, `char *`, `char const*const*`, etc. adn their intents is tricky business, and I had missed a case in an if statement.
It should now be fixed. I was able to compile using Intel oneAPI 2025.2
`ifx -fpp -warn all -stand f2018 -Iinclude -c src/gl.F90`
